### ISSUE TITLE
[BUG] Issue with static covariates with TFTModel

### ISSUE THREAD

**Issue by egiacomazzi** [unit8co/darts#1212]
**Describe the bug**
TFTModel tells me that it does not know the argument _categorical_embedding_sizes_ while model definition.
The argument is described in the [TFTModel documentation](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#temporal-fusion-transformer-tft) and was used according to the given [example](https://unit8co.github.io/darts/examples/15-static-covariates.html).

```
Traceback (most recent call last):
  File "/Users/elena/Work/Code/TFT/train_TFT_multi_CPU.py", line 147, in <module>
    model = define_model(args, run_name)
  File "/Users/elena/Work/Code/TFT/train_TFT_multi_CPU.py", line 60, in define_model
    model = TFTModel(input_chunk_length=args.back_window,
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/models/forecasting/forecasting_model.py", line 92, in __call__
    return super().__call__(**all_params)
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/models/forecasting/tft_model.py", line 774, in __init__
    super().__init__(**self._extract_torch_model_params(**model_kwargs))
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 435, in _extract_torch_model_params
    cls._validate_model_params(**kwargs)
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 426, in _validate_model_params
    raise_if(
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/logging.py", line 106, in raise_if
    raise_if_not(not condition, message, logger)
  File "/Users/elena/Work/Environment/hiwiDarts/lib/python3.9/site-packages/darts/logging.py", line 80, in raise_if_not
    raise ValueError(message)
ValueError: Invalid model creation parameters. Model `TFTModel` has no args/kwargs `['categorical_embedding_sizes']`
```
**To Reproduce**
The code I used to define the model:
```
def define_model(args, model_name):
    wandb_logger = WandbLogger() 
    lr_monitor = LearningRateMonitor(logging_interval='step')
    n_categories = 70  # how many knoten exist
    embedding_size = 70  # embed the categorical variable into a numeric vector of size 70
    categorical_embedding_sizes = {"Knoten": (n_categories, embedding_size)}

    model = TFTModel(input_chunk_length=args.back_window,
                output_chunk_length=args.horizon,
                hidden_size=args.hidden,
                lstm_layers=args.lstm_layers,
                num_attention_heads=args.att_heads,
                full_attention=args.full_att,
                dropout=args.dropout,
                batch_size=args.batch_size,
                n_epochs=args.epochs,
                likelihood=args.likelihood, 
                loss_fn=args.loss,
                lr_scheduler_cls=args.decay_lr_class,
                lr_scheduler_kwargs={"gamma":0.1},
                random_state=args.rand, 
                force_reset=True,
                log_tensorboard=True,
                save_checkpoints=True,
                model_name=model_name,
                categorical_embedding_sizes=categorical_embedding_sizes,
                work_dir = "./models/cpu/",
                pl_trainer_kwargs={"accelerator": "cpu", "logger":[wandb_logger], "callbacks":[lr_monitor]}) #  "gpus": 1, , "callbacks":[lr_monitor]
    return model

```

**Expected behavior**
I would like the model to know the argument and recognize the static covariates in the dataset for training.

**System (please complete the following information):**
 - Python version: 3.9.12
 - darts version: 0.20.0

Thank you for your help!

**Comment by dennisbader** [comment]
Categorical static covariate support for TFTModel was added in darts==0.21.0. 
It should work when you upgrade your darts version!
