### ISSUE TITLE
[BUG] TimeSeries with CustomBusinessHour frequency cannot be accessed by indexing

### ISSUE THREAD

**Issue by DavidKleindienst** [unit8co/darts#1377]
**Describe the bug**
A `TimeSeries` created with `CustomBusinessHour` frequency cannot be properly accessed with `ts[index]`. Some indexes (e.g. 0, 8) work, while most (e.g. 1,2,3,4,5,6,7) cause the following error:
```
Traceback (most recent call last):
  File "C:\Users\...\site-packages\pandas\core\arrays\datetimelike.py", line 962, in _validate_frequency
    raise ValueError
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\...\site-packages\darts\timeseries.py", line 4086, in __getitem__
    _set_freq_in_xa(xa_)  # indexing may discard the freq so we restore it...
  File "C:\Users\...\site-packages\darts\timeseries.py", line 4002, in _set_freq_in_xa
    xa_.get_index(self._time_dim).freq = self._freq
  File "C:\Users\...\site-packages\pandas\core\indexes\extension.py", line 78, in fset
    setattr(self._data, name, value)
  File "C:\Users\...\site-packages\pandas\core\arrays\datetimelike.py", line 891, in freq
    self._validate_frequency(self, value)
  File "C:\Users\...\site-packages\pandas\core\arrays\datetimelike.py", line 973, in _validate_frequency
    raise ValueError(
ValueError: Inferred frequency None from passed values does not conform to passed frequency CBH
```
**To Reproduce**
```python
import pandas as pd
import datetime as dt
import numpy as np
from darts import TimeSeries

# Create TimeSeries with CustomBusinessHour frequency
freq = pd.offsets.CustomBusinessHour(start="9:00", end="17:00", weekmask="Mon Tue")
timestamps = pd.date_range(start=dt.datetime(2020,1,1), end=dt.datetime(2020,2,1), freq=freq)
data = pd.DataFrame({"time": timestamps,"values": np.random.random(len(timestamps))})
ts = TimeSeries.from_dataframe(data, "time", ["values"], freq=freq)

# ts[0] will work as expected, but ts[1] will error
ts[1]
```

**Expected behavior**
TimeSeries entries can be properly accessed by `ts[index]` notation

**System (please complete the following information):**
 - Python version: 3.10
 - darts version 0.21.0

**Comment by DavidKleindienst** [comment]
Actually, this seems to be a pandas issue, so I opened a bug report on their Github
https://github.com/pandas-dev/pandas/issues/49835

**Comment by hrzn** [comment]
Thanks for the update @DavidKleindienst, closing this one here.
