### ISSUE TITLE
[BUG] <DateOffset: hours=4> is a non-fixed frequency in WindowTransformer's rolling transform 

### ISSUE THREAD

**Issue by JQGoh** [unit8co/darts#1662]
**Describe the bug**
When applying a rolling mean to a regularly spaced, hourly sample series, we encounter an error stating that
 `ValueError: <DateOffset: hours=4> is a non-fixed frequency`
The error is unexpected because `hours=4` is a fixed frequency, not like an offset in a month unit.

**To Reproduce**
``` python
import numpy as np
import pandas as pd

from darts import TimeSeries
from darts.dataprocessing.transformers.window_transformer import WindowTransformer

n_steps = 36
series = TimeSeries.from_times_and_values(
    pd.date_range(start="2023-01-01", freq="1H", periods=n_steps), np.arange(n_steps)
)

transformer = WindowTransformer(
    transforms={
        "function": "mean",
        "mode": "rolling",
        "window": pd.DateOffset(hours=4),
    }
)
transformed = transformer.transform(series)

```

**Expected behavior**
Expect that the transformer.transform() shall work without an issue such that the output `transformed` is the same as the output of 
```
WindowTransformer(
    transforms={
        "function": "mean",
        "mode": "rolling",
        "window": 4,
    }
)
```
since the series is regularly spaced.

**System (please complete the following information):**
 - Python version: 3.9.16
 - darts version: 0.23.1 

**Additional context**
The complete error log
```
(science) ~/Desktop $ python bug.py
Traceback (most recent call last):
  File "/Users/jingqianggoh/Desktop/bug.py", line 21, in <module>
    transformed = transformer.transform(series)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/darts/dataprocessing/transformers/base_data_transformer.py", line 183, in transform
    transformed_data = _parallel_apply(
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/darts/utils/utils.py", line 295, in _parallel_apply
    returned_data = Parallel(n_jobs=n_jobs)(
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/darts/dataprocessing/transformers/window_transformer.py", line 161, in ts_transform
    return series.window_transform(**kwargs_dict)
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/darts/timeseries.py", line 3452, in window_transform
    (window_mode, window_mode_kwargs), (fn, function_kwargs) = _get_kwargs(
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/darts/timeseries.py", line 3369, in _get_kwargs
    getattr(pd.DataFrame(), window_mode.__name__)(
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/pandas/core/generic.py", line 11999, in rolling
    return Rolling(
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/pandas/core/window/rolling.py", line 165, in __init__
    self._validate()
  File "/Users/jingqianggoh/.pyenv/versions/science/lib/python3.9/site-packages/pandas/core/window/rolling.py", line 1847, in _validate
    self._win_freq_i8 = freq.nanos
  File "pandas/_libs/tslibs/offsets.pyx", line 821, in pandas._libs.tslibs.offsets.BaseOffset.nanos.__get__
ValueError: <DateOffset: hours=4> is a non-fixed frequency
```

**Comment by madtoinou** [comment]
Hi,

From my understanding `pd.DateOffSet(hours=4)` is not really a duration but rather a single value used to perform operation on `pd.TimeStamp` whereas the darts `WindowTransformer` expect a "time-span" (which could be considered as an implicit "time  range"): by using `pd.Timedelta(hours=4)` instead, the transform behaves as expected:

```python
transformer = WindowTransformer(transforms={
        "function": "mean",
        "mode": "rolling",
        "window": pd.Timedelta(hours=4)}
)

transformed = transformer.transform(series)

series[:4].values()
>>> array([[0.], [1.], [2.], [3.]])

transformed[:4].values()
>>> array([[0. ], [0.5], [1. ], [1.5]])
```

**Comment by JQGoh** [comment]
Hi @madtoinou  Thanks for looking into this. 

The documentation explains that the parameter `window` expects that [if an offset, the time period of each window.](https://unit8co.github.io/darts/generated_api/darts.dataprocessing.transformers.window_transformer.html#:~:text=If%20an%20offset%2C%20the%20time%20period%20of%20each%20window), I mistaken the offset referring to pandas `DateOffset` type.

If `pd.Timedelta` is the only valid choice for the `window` parameter in WindowTransformer, I suggest that we could improve this by explicitly mentioning this in the documentation. Besides, I noticed that the [test cases in test_window_transformations.py](https://github.com/unit8co/darts/blob/be21ed8d0cce935532cccba1f0172d17a44f057e/darts/tests/dataprocessing/transformers/test_window_transformations.py) mainly consider `window` parameter of integer format only. We could add a few test cases with `pd.Timedelta`.

Let me know what do you think about this and I am happy to open an PR for this.

**Comment by madtoinou** [comment]
The documentation is indeed misleading, it would probably be clearer to mention `pd.Timedelta` and the unit tests should indeed cover these cases.

You contribution is very welcome, can't wait to see your PR!
