### ISSUE TITLE
Error installing darts in virtual env

### ISSUE THREAD

**Issue by bustosxaus** [unit8co/darts#1706]
Hi, 

I am trying to install darts in a virtual environment in popos Linux and I get the following error:

```python
ERROR: Exception:
Traceback (most recent call last):
  File "/home/tron/research/darts/darts/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/tron/research/darts/darts/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/tron/research/darts/darts/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/tron/research/darts/darts/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/tron/research/darts/darts/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

Thank you in advance for any help.

**Comment by madtoinou** [comment]
Hi @bustosxaus,

The error seems to come from pip itself, may I ask you which tool did you use to create your virtual environment?

**Comment by bustosxaus** [comment]
Thank you for the help, the problem was with pip, I used `venv` to create the virtual environment and the pip version was 22.0.2, so I ran `pip install -U pip` and `pip install -U setuptools wheel` and then installed `darts` with `pip install darts`, and everything worked, thank you!
