### ISSUE TITLE
[BUG] Poetry installation fails.

### ISSUE THREAD

**Issue by davide-burba** [unit8co/darts#1747]
**Describe the bug**
Installing darts with poetry fails. The failure happens only when there are additional packages to install (pandas in the example).
The installation succeeds if darts is the only dependency.
The installation with pip succeeds (with `poetry run pip install`).

The issue is related to the installation of `lttbc` 0.2.1 not supporting PEP 517 builds. Even trying to install `lttbc` alone leads to the same error. However, I don't understand why it doesn't happen when installing `darts` only. 

Here are the logs from `poetry install`:

```
Creating virtualenv demo in /Users/MyUser/Documents/personal/projects/darts-test/.venv
Updating dependencies
Resolving dependencies... (31.7s)

Writing lock file

Package operations: 136 installs, 1 update, 0 removals

  • Installing six (1.16.0)
  • Installing appdirs (1.4.4)
  • Installing asttokens (2.2.1)
  • Installing executing (1.2.0)
  • Installing markupsafe (2.1.2)
  • Installing numpy (1.24.3)
  • Installing parso (0.8.3)
  • Installing platformdirs (3.5.0)
  • Installing ptyprocess (0.7.0)
  • Installing pure-eval (0.2.2)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2023.3)
  • Updating setuptools (67.6.1 -> 67.7.2)
  • Installing traitlets (5.9.0)
  • Installing tzdata (2023.3)
  • Installing wcwidth (0.2.6)
  • Installing zipp (3.15.0)
  • Installing appnope (0.1.3)
  • Installing backcall (0.2.0)
  • Installing blinker (1.6.2)
  • Installing click (8.1.3): Installing...
  • Installing click (8.1.3)
  • Installing decorator (5.1.1)
  • Installing fs (2.4.16): Installing...
  • Installing fs (2.4.16)
  • Installing importlib-metadata (6.6.0)
  • Installing itsdangerous (2.1.2)
  • Installing jedi (0.18.2)
  • Installing jinja2 (3.1.2)
  • Installing jupyter-core (5.3.0)
  • Installing matplotlib-inline (0.1.6)
  • Installing packaging (23.1)
  • Installing pandas (2.0.1)
  • Installing pexpect (4.8.0)
  • Installing pickleshare (0.7.5)
  • Installing prompt-toolkit (3.0.38)
  • Installing pyarrow (12.0.0)
  • Installing pygments (2.15.1)
  • Installing pyzmq (25.0.2)
  • Installing stack-data (0.6.2)
  • Installing tenacity (8.2.2)
  • Installing tornado (6.3.1)
  • Installing typing-extensions (4.5.0)
  • Installing werkzeug (2.3.3)
  • Installing certifi (2023.5.7): Installing...
  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing comm (0.1.3)
  • Installing dash-core-components (2.0.0)
  • Installing dash-html-components (2.0.0)
  • Installing dash-table (5.0.0)
  • Installing debugpy (1.6.7): Installing...
  • Installing debugpy (1.6.7)
  • Installing flask (2.3.2)
  • Installing frozenlist (1.3.3)
  • Installing idna (3.4)
  • Installing ipython (8.12.2)
  • Installing jupyter-client (8.2.0)
  • Installing mpmath (1.3.0)
  • Installing multidict (6.0.4)
  • Installing nest-asyncio (1.5.6)
  • Installing plotly (5.14.1)
  • Installing psutil (5.9.5)
  • Installing triad (0.8.7)
  • Installing urllib3 (2.0.2)
  • Installing adagio (0.2.4): Installing...
  • Installing adagio (0.2.4)
  • Installing aiosignal (1.3.1)
  • Installing ansi2html (1.8.0)
  • Installing antlr4-python3-runtime (4.11.1): Installing...
  • Installing antlr4-python3-runtime (4.11.1)
  • Installing async-timeout (4.0.2)
  • Installing attrs (23.1.0)
  • Installing dash (2.9.3)
  • Installing filelock (3.12.0)
  • Installing greenlet (2.0.2)
  • Installing ipykernel (6.22.0)
  • Installing joblib (1.2.0)
  • Installing networkx (3.1)
  • Installing patsy (0.5.3)
  • Installing requests (2.30.0)
  • Installing retrying (1.3.4)
  • Installing scipy (1.9.3)
  • Installing sympy (1.11.1)
  • Installing threadpoolctl (3.1.0)
  • Installing yarl (1.9.2)
  • Installing aiohttp (3.8.4): Installing...
  • Installing contourpy (1.0.7): Pending...
  • Installing aiohttp (3.8.4)
  • Installing contourpy (1.0.7)
  • Installing cycler (0.11.0)
  • Installing cython (0.29.34)
  • Installing dash-bootstrap-components (0.13.1)
  • Installing ephem (4.1.4)
  • Installing fonttools (4.39.3)
  • Installing fugue-sql-antlr (0.1.6)
  • Installing hijri-converter (2.3.1)
  • Installing importlib-resources (5.12.0)
  • Installing jupyter-dash (0.4.2)
  • Installing kiwisolver (1.4.4)
  • Installing korean-lunar-calendar (0.3.1)
  • Installing llvmlite (0.40.0): Installing...
  • Installing lttbc (0.2.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_ext
  building 'lttbc' extension
  Traceback (most recent call last):
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 29, in <module>
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 590, in compile
  • Installing lttbc (0.2.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_ext
  building 'lttbc' extension
  Traceback (most recent call last):
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 29, in <module>
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 590, in compile
  • Installing llvmlite (0.40.0)
  • Installing lttbc (0.2.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_ext
  building 'lttbc' extension
  Traceback (most recent call last):
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/MyUser/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 29, in <module>
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 590, in compile
      macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 348, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/var/folders/_c/mh_rhxl575zbxsb2k5299zbc0000gn/T/tmp57wj8jc6/.venv/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 1213, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
    File "<string>", line 18, in __str__
  ModuleNotFoundError: No module named 'numpy'


  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with lttbc (0.2.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "lttbc (==0.2.1)"'.

  • Installing orjson (3.8.11)
  • Installing pillow (9.5.0)
  • Installing pymeeus (0.5.12)
  • Installing pyparsing (3.0.9)
  • Installing qpd (0.4.1)
  • Installing scikit-learn (1.2.2)
  • Installing sqlalchemy (2.0.12)
  • Installing sqlglot (12.1.0)
  • Installing statsmodels (0.14.0)
  • Installing torch (2.0.0)
  • Installing tqdm (4.65.0)
  • Installing trace-updater (0.0.6)
```

**To Reproduce**
 
Here's the content of `pyproject.toml`:

```
[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
darts = "^0.24.0"
pandas = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Expected behavior**
A successful installation.

**System (please complete the following information):**
 - Python version: 3.8.16
 - darts version: 0.24.0
- poetry version: 1.4.2
- MacOS BigSur (11.4) with Intel chip

**Additional context**
I tried different configurations, e.g install pandas before darts (and viceversa), using an upgraded python version, specify a downgraded lttbc version, but I always got the same error.

I always use poetry to manage my dependencies, I found it much cleaner/lighter than Conda, and I'd like to integrate darts in my stack, so any help is highly appreciated!

**Comment by madtoinou** [comment]
Thank you @jlopezpena for the update.

Closing this for now, please reopen if the problem persists.
