### ISSUE TITLE
cannot load model

### ISSUE THREAD

**Issue by mbenami** [unit8co/darts#1905]
**Describe the bug**
I'm trying to train NBEATSModel on M4 dataset 
my script is 
```
np.random.seed(42)
torch.manual_seed(42)

nbeats_param = {
             'generic_architecture': True,
             'num_stacks': 18,
             'num_blocks': 3,
             'num_layers': 3,
             'layer_widths': 180,
             'expansion_coefficient_dim': 6,
             'trend_polynomial_degree': 2,
             'dropout': 0.0,
             'activation': 'ReLU',
             'input_chunk_length': 36,
             'output_chunk_length': 12,
             'batch_size': 1024 * 4,
             'nr_epochs_val_period': 1,
             'loss_fn': SmapeLoss(),
             'optimizer_kwargs': {
                 'lr': 0.0005
                 },
             'pl_trainer_kwargs':{
                 'enable_progress_bar': True,
                 'accelerator': 'gpu'
             },
             'log_tensorboard': True,
             "save_checkpoints":True,
}
nbeats_model_m4 = NBEATSModel(**nbeats_param)

nbeats_model_m4.fit(
    m4_series,
    epochs=100
)
```

when I'm trying to load the ckpt with (middle of the training not final one)
```
nbeats_model_m4 = NBEATSModel.load("path to model.ckpt")
```
I get error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/darts/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1586, in load
    model._fit_called = False
AttributeError: 'dict' object has no attribute '_fit_called'
```

any idea what I did wrong? 
also, I'm training with 4 GPUs and I would like to predict also with CPU 
is that possible?

Thanks for the help

**To Reproduce**
Steps to reproduce the behavior, preferably code snippet.

**Expected behavior**

**System (please complete the following information):**
 - Python version: [e.g. 3.8]
 - darts version [e.g. 0.24.0]

**Additional context**

**Comment by mbenami** [comment]
ok solve this by creating a new model with the same parameters and loading just the weights 
```
model_nbeats_my = NBEATSModel(**nbeats_param)
model_nbeats_my.load_weights("path to ckpt without .ckpt extension ",map_location=torch.device('cpu'))
model_nbeats_my.to_cpu()
```
