### ISSUE TITLE
[BUG] Weekly data doesn't work when setting freq = 7 / freq = 'W'

### ISSUE THREAD

**Issue by RodrigoZepeda** [unit8co/darts#1910]
**Describe the bug**
Construction of `TimeSeries.from_dataframe` gives an error when using weekly data without missing data. 
This happens both when setting `freq="W"` or `freq=7` . 

**To Reproduce**
```
import pandas as pd
from darts import TimeSeries

df = pd.DataFrame({"date": ["2016-01-04","2016-01-11","2016-01-18"], "value": [1.0,2.0,3.0]})
df.date = pd.to_datetime(df.date, format="%Y-%m-%d")
```

The weekly frequency gives this error:
```
TimeSeries.from_dataframe(df, "date","value", freq="W")
```

```
ValueError: Could not correctly fill missing dates with the observed/passed frequency `freq='W'`. Not all input time stamps contained in the newly created TimeSeries. For more information about frequency aliases, read https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4339fd497c41>", line 6, in <module>
    TimeSeries.from_dataframe(df, "date","value", freq="W")
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 714, in from_dataframe
    return cls.from_xarray(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 379, in from_xarray
    xa_ = cls._restore_xarray_from_frequency(xa, freq=freq)
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 4471, in _restore_xarray_from_frequency
    raise_log(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/logging.py", line 129, in raise_log
    raise exception
ValueError: Could not correctly fill missing dates with the observed/passed frequency `freq='W'`. Not all input time stamps contained in the newly created TimeSeries. For more information about frequency aliases, read https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
```

While the integer frequency gives this one:
```
TimeSeries.from_dataframe(df, "date","value", freq=7)
```

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-26421ada9ee0>", line 1, in <module>
    TimeSeries.from_dataframe(df, "date","value", freq=7)
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 714, in from_dataframe
    return cls.from_xarray(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 379, in from_xarray
    xa_ = cls._restore_xarray_from_frequency(xa, freq=freq)
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/darts/timeseries.py", line 4453, in _restore_xarray_from_frequency
    resampled_time_index = resampled_time_index.asfreq(freq)
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/pandas/core/series.py", line 5695, in asfreq
    return super().asfreq(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/pandas/core/generic.py", line 8347, in asfreq
    return asfreq(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/pandas/core/resample.py", line 2232, in asfreq
    dti = date_range(obj.index.min(), obj.index.max(), freq=freq)
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/pandas/core/indexes/datetimes.py", line 945, in date_range
    dtarr = DatetimeArray._generate_range(
  File "/usr/local/Caskroom/miniconda/base/envs/timeseries/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 398, in _generate_range
    freq = to_offset(freq)
  File "pandas/_libs/tslibs/offsets.pyx", line 4102, in pandas._libs.tslibs.offsets.to_offset
  File "pandas/_libs/tslibs/offsets.pyx", line 4203, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: 7
```

It works however if we ignore the `freq` parameter
```
TimeSeries.from_dataframe(df, "date","value")
```

**Expected behavior**
`TimeSeries.from_dataframe` to work both with `freq` and without it for weekly data with non-missing values. Or maybe I am reading the documentation wrong?

**System*
 - Python 3.10.12
 - darts 0.24.0

**Comment by dennisbader** [comment]
The correct frequency for your data is "W-MON" (weekly starting on Monday). You can see this when printing the frequency of the series (Darts automatically tries to infer the frequency for you):

```
>>> series = TimeSeries.from_dataframe(df, "date","value")
>>> print(series.freq_str)
W-MON
```

From the pandas documentation [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#anchored-offsets) you can see that  "W" corresponds to "W-SUN" (first line).

So giving the correct frequency will work:
```
TimeSeries.from_dataframe(df, "date","value", freq="W-MON")
```
 
Integer values for the frequency are only allowed for integer/range-indexed data.

**Comment by RodrigoZepeda** [comment]
Thanks for the answer. I'm closing the issue.
