### ISSUE TITLE
[BUG] Unittest may fail depending on the version of pmdarima and statsmodels

### ISSUE THREAD

**Issue by norihitoishida** [unit8co/darts#195]
## Describe the bug
Unittest may fail depending on the version of pmdarima and statsmodels.

## System (please complete the following information)
 - Python version : 3.8.2
 - darts version : 0.2.3
 - OS : Ubuntu 20.04.1 LTS (Focal Fossa)

## To Reproduce
I tried 3 combinations of the following.
|pmdarima|statsmodels|results|
|---|---|---|
|1.6.1(not latest)|0.11.1(not latest)|OK|
|1.6.1(not latest)|0.12.0(latest)|`test_autoregression_models.py` fails because of Exponential smoothing model|
|1.7.1(latest)|0.11.1(not latest)|`test_autoregression_models.py` fails because of Auto-ARIMA model|

 I didn't try the case that both libraries are latest version (pmdarima 1.7.1, statsmodels 0.12) because pmdarima 1.7.1 requires statsmodels<0.12. Please see also #194.

## Suggention & Question
This error is likely caused by the threshold in [this section](https://github.com/unit8co/darts/blob/00a964aa9066b2642826335619f5d5483df8c0fc/darts/tests/test_autoregression_models.py#L30).
Does anyone know how this threshold is determined?
Also, do you think it is reasonable to change the thresholds so that no errors occur?
I would like to get your opinions.

### pmdarima==1.6.1(not latest) statsmodels==0.11.1(not latest)
```
MY_DIR/darts$ python3 -m pip install -q pmdarima==1.6.1 statsmodels==0.11.1
MY_DIR/darts$ python3 -m unittest
./home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
loading checkpoint_3.pth.tar
....loading checkpoint_3.pth.tar
......../home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/.local/lib/python3.8/site-packages/Cython/Build/Inline.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/statespace/sarimax.py:975: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:568: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
./home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/git/darts/darts/models/theta.py:108: RuntimeWarning: invalid value encountered in double_scalars
  drift = self.coef * np.array([i + (1 - (1 - self.alpha) ** self.length) / self.alpha for i in range(0, n)])
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:568: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
./home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 201.50it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 179.40it/s]
.../home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:568: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
................................................/home/norihitoishida/git/darts/darts/tests/test_timeseries.py:410: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  TimeSeries.from_series(pd.Series(), freq='D')
................................................
----------------------------------------------------------------------
Ran 118 tests in 37.855s

OK
```

### pmdarima==1.6.1(not latest) statsmodels==0.12.0(latest)
```
MY_DIR/darts$ python3 -m pip install -q pmdarima==1.6.1 statsmodels==0.12.0
MY_DIR/darts$ python3 -m unittest
./home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
loading checkpoint_3.pth.tar
....loading checkpoint_3.pth.tar
......../home/norihitoishida/git/darts/darts/models/exponential_smoothing.py:62: FutureWarning: the 'damped'' keyword is deprecated, use 'damped_trend' instead
  hw_model = hw.ExponentialSmoothing(series.values(),
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters/model.py:427: FutureWarning: After 0.13 initialization must be handled at model creation
  warnings.warn(
F/home/norihitoishida/.local/lib/python3.8/site-packages/Cython/Build/Inline.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/arima_model.py:472: FutureWarning: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been deprecated in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and
statsmodels.tsa.SARIMAX. These will be removed after the 0.12 release.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained.

To silence this warning and continue using ARMA and ARIMA until they are
removed, use:

import warnings
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARMA',
                        FutureWarning)
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARIMA',
                        FutureWarning)

  warnings.warn(ARIMA_DEPRECATION_WARN, FutureWarning)
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters/model.py:427: FutureWarning: After 0.13 initialization must be handled at model creation
  warnings.warn(
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:662: FutureWarning: fft=True will become the default after the release of the 0.12 release of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
./home/norihitoishida/git/darts/darts/models/exponential_smoothing.py:62: FutureWarning: the 'damped'' keyword is deprecated, use 'damped_trend' instead
  hw_model = hw.ExponentialSmoothing(series.values(),
/home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 199.28it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 196.29it/s]
.../home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:662: FutureWarning: fft=True will become the default after the release of the 0.12 release of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
................................................/home/norihitoishida/git/darts/darts/tests/test_timeseries.py:410: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  TimeSeries.from_series(pd.Series(), freq='D')
................................................
======================================================================
FAIL: test_models_performance (darts.tests.test_autoregression_models.AutoregressionModelsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/norihitoishida/git/darts/darts/tests/test_autoregression_models.py", line 59, in test_models_performance
    self.assertTrue(current_mape < max_mape, "{} model exceeded the maximum MAPE of {}."
AssertionError: False is not true : Exponential smoothing model exceeded the maximum MAPE of 4.8.with a MAPE of 5.5900253625464575

----------------------------------------------------------------------
Ran 118 tests in 39.151s

FAILED (failures=1)
```
### pmdarima==1.7.1(latest) statsmodels==0.11.1(not latest)
```
MY_DIR/darts$ python3 -m pip install -q pmdarima==1.7.1 statsmodels==0.11.1
MY_DIR/darts$ python3 -m unittest
./home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
loading checkpoint_3.pth.tar
....loading checkpoint_3.pth.tar
......../home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/.local/lib/python3.8/site-packages/Cython/Build/Inline.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "
F/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/git/darts/darts/models/theta.py:108: RuntimeWarning: invalid value encountered in double_scalars
  drift = self.coef * np.array([i + (1 - (1 - self.alpha) ** self.length) / self.alpha for i in range(0, n)])
/home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:568: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
./home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/holtwinters.py:743: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  warn("Optimization failed to converge. Check mle_retvals.",
/home/norihitoishida/.local/lib/python3.8/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 200.28it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 198.92it/s]
.../home/norihitoishida/.local/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:568: FutureWarning: fft=True will become the default in a future version of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(
................................................/home/norihitoishida/git/darts/darts/tests/test_timeseries.py:410: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  TimeSeries.from_series(pd.Series(), freq='D')
................................................
======================================================================
FAIL: test_models_performance (darts.tests.test_autoregression_models.AutoregressionModelsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/norihitoishida/git/darts/darts/tests/test_autoregression_models.py", line 59, in test_models_performance
    self.assertTrue(current_mape < max_mape, "{} model exceeded the maximum MAPE of {}."
AssertionError: False is not true : Auto-ARIMA model exceeded the maximum MAPE of 13.7.with a MAPE of 30.32851040186142

----------------------------------------------------------------------
Ran 118 tests in 41.443s

FAILED (failures=1)

```

**Comment by pennfranc** [comment]
Hi @norihitoishida. Good catch, thanks for pointing this out! However, this should be resolved in the next release, and should not currently be a problem on the `develop` branch since we are now using fixed versions in our requirements file. If you branch off of develop for #192 and install darts in a fresh environment this should not be an issue!

**Comment by norihitoishida** [comment]
Sorry, I missed that.
Thanks for letting me know, @pennfranc !
