### ISSUE TITLE
[BUG] Cannot import darts after installation

### ISSUE THREAD

**Issue by wangle10** [unit8co/darts#2009]
**Describe the bug**
Cannot import darts package，环境为python3.8 darts0.26.0，The specific code is as follows
**To Reproduce**
from darts import TimeSeries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/python3.8/lib/python3.8/site-packages/darts/__init__.py", line 11, in <module>
    from .timeseries import TimeSeries, concatenate
  File "/data/python3.8/lib/python3.8/site-packages/darts/timeseries.py", line 51, in <module>
    from scipy.stats import kurtosis, skew
  File "/data/python3.8/lib/python3.8/site-packages/scipy/stats/__init__.py", line 485, in <module>
    from ._stats_py import *
  File "/data/python3.8/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
    from . import distributions
  File "/data/python3.8/lib/python3.8/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/data/python3.8/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 25, in <module>
    from scipy import integrate
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/data/python3.8/lib/python3.8/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/data/python3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/python3.8/lib/python3.8/site-packages/scipy/integrate/__init__.py", line 96, in <module>
    from ._ivp import (solve_ivp, OdeSolution, DenseOutput,
  File "/data/python3.8/lib/python3.8/site-packages/scipy/integrate/_ivp/__init__.py", line 2, in <module>
    from .ivp import solve_ivp
  File "/data/python3.8/lib/python3.8/site-packages/scipy/integrate/_ivp/ivp.py", line 4, in <module>
    from .radau import Radau
  File "/data/python3.8/lib/python3.8/site-packages/scipy/integrate/_ivp/radau.py", line 34, in <module>
    TI_COMPLEX = TI[1] + 1j * TI[2]
TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations

**Expected behavior**

**System (please complete the following information):**
 - Python version: [e.g. 3.8]
 - darts version [e.g. 0.26.0]

**Additional context**

**Comment by dennisbader** [comment]
Hi @wangle10, and sorry for the late response.

A few things that you can try:
- create a clean new environment and freshly install darts in there
- it can be that some packages are not compatible with python 3.8. anymore. If you don't have to use 3.8, python 3.9+ should work fine
- if both of the options above don't work for you, we have to dig deeper how to resolve the dependency issues
