### ISSUE TITLE
Experiencing an error while utilizing darts within the GUI module of PySide6.

### ISSUE THREAD

**Issue by allentern** [unit8co/darts#2232]
Darts is an excellent library, and I would like to extend my gratitude to the development team. 
Through learning, I have managed to accomplish some forecasting tasks using darts. 
Recently, I encountered an issue where I intended to create a GUI tool with PySide6 that integrates darts to facilitate model training in a graphical manner. During testing, I found that after importing a specific model from from darts.models import ..., executing the code results in an error, the message of which reads as follows:
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\ews\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "d:\0.ts_auto\dmodeler\modeler.py", line 14, in <module>
    from view.training_interface import TrainingInterface
  File "d:\0.ts_auto\dmodeler\view\training_interface.py", line 25, in <module>
    from darts.models import TCNModel, NHiTSModel, TiDEModel
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\darts\models\__init__.py", line 65, in <module>
    from darts.models.forecasting.croston import Croston
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\darts\models\forecasting\croston.py", line 8, in <module>
    from statsforecast.models import TSB as CrostonTSB
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\statsforecast\__init__.py", line 3, in <module>
    from .core import StatsForecast
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\statsforecast\core.py", line 21, in <module>
    import utilsforecast.processing as ufp
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\utilsforecast\processing.py", line 21, in <module>
    from .compat import DataFrame, Series, pl, pl_DataFrame, pl_Series
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\utilsforecast\compat.py", line 46, in <module>
    from numba import njit  # noqa: F04
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\__init__.py", line 89, in <module>
    from numba.core.decorators import (cfunc, jit, njit, stencil,
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\core\registry.py", line 6, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\core\dispatcher.py", line 22, in <module>
    from numba.core.caching import NullCache, FunctionCache
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\core\caching.py", line 19, in <module>
    from numba.misc.appdirs import AppDirs
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\numba\misc\appdirs.py", line 507, in <module>
    import win32com.shell
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "D:\ProgramData\Miniconda3\envs\ews\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "D:\ProgramData\Miniconda3\envs\ews\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "D:\ProgramData\Miniconda3\envs\ews\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "D:\ProgramData\Miniconda3\envs\ews\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'D:\\ProgramData\\Miniconda3\\envs\\ews\\lib\\site-packages\\win32\\pywintypes39.dll'

**To Reproduce**
Testing Code Example:
from PySide6.QtWidgets import QWidget, QHBoxLayout, QFrame, QFileDialog, QVBoxLayout, QListWidgetItem
from qfluentwidgets import FluentIcon, CardWidget, CheckBox, ListWidget, setTheme, Theme, SpinBox, DateTimeEdit
from PySide6.QtCore import Qt, QThread, Signal
from darts import TimeSeries
from darts.models import TCNModel, NHiTSModel, TiDEModel
...

Running standalone test programs for PySide6 and darts both work without any issues. 
However, when integrating darts into the GUI module of PySide6, it results in an error.

**System (please complete the following information):**
 - windows 11, conda env,  PySide6 6.4.2, darts 0.27.2
 - Python version: [e.g. 3.9.18]
 - darts version [e.g. 0.27.2]

**Additional context**
The error appears to stem from attempting to interpret `pywintypes39.dll` as source code, which leads to the error. 
Being a beginner, I have tried several potential solutions but have yet to resolve the issue. 
I am wondering if anyone else has encountered a similar problem before and might have advice?

**Comment by allentern** [comment]
It appears to be a bug in PySide6, switching to PyQt6 resolves the issue.
