### ISSUE TITLE
[BUG] TypeError then predicting in multi-gpu scenario

### ISSUE THREAD

**Issue by nejox** [unit8co/darts#2265]
**Describe the bug**
After training a TFT with `ddp_spawn`strategy on multiple gpus in Amazon SageMaker the returned prediction of the trainer is None, leading to an `TypeError: 'NoneType' object is not iterable` in `torch_forecasting_model`.

**To Reproduce**
Code to reproduce the problem. I tried it locally with `"accelerator":"cpu"`also (don't know if this is even a valid approach) and end up with the same error.

```
import torch
from darts.models import TFTModel
from darts.datasets import AirPassengersDataset

if __name__ == "__main__":
    torch.multiprocessing.freeze_support()
    series = AirPassengersDataset().load()
    series = [series] * 10

    model = TFTModel(
        input_chunk_length=12,
        output_chunk_length=6,
        add_relative_index=True,
        pl_trainer_kwargs={
            "accelerator": "gpu",
            "strategy": "ddp_spawn",
            "devices": "2"
           }
    )
    model.fit(series, epochs=10)
    preds = model.predict(n=6, series=series, num_samples=100)
    print("len(preds)", len(preds), "len(series)", len(series))
```
=> leads to:
```
Traceback (most recent call last):
  File ".../src/test_multigpu.py", line 21, in <module>
    preds = model.predict(n=6, series=series, num_samples=100)
  File ".../darts/models/forecasting/torch_forecasting_model.py", line 2784, in predict
    return super().predict(
  File ".../darts/utils/torch.py", line 112, in decorator
    return decorated(self, *args, **kwargs)
  File ".../darts/models/forecasting/torch_forecasting_model.py", line 1371, in predict
    predictions = self.predict_from_dataset(
  File ".../darts/utils/torch.py", line 112, in decorator
    return decorated(self, *args, **kwargs)
  File ".../darts/models/forecasting/torch_forecasting_model.py", line 1519, in predict_from_dataset
    return [ts for batch in predictions for ts in batch]
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**
Successfully predict values, does not need to be multi gpu prediction as I only need the speed up for training.

**System (please complete the following information):**
 - Python version: 3.9
 - darts version: 0.27.2
 - lightning version: 2.1.3
 - torch version: 2.1.0
 - OS: macOS 14.2.1 (23C71)

**Additional context**
Lightning documentation recommends ddp and not to use ddp_spawn but darts only supports ddp_spawn, right? I couldn't get ddp running as i had problems with multiple executions of my script due to 1 process per gpu and thus multiple checkpoints created.

**Comment by BohdanBilonoh** [comment]
Faced the same issue. Found that distributed Lighting inference requires `BasePredictionWriter` https://lightning.ai/docs/pytorch/stable/deploy/production_basic.html#enable-distributed-inference

**Comment by dennisbader** [comment]
@BohdanBilonoh, would you mind sharing your use of the `BasePredictionWriter` to help other users that face the same issue? Would also be interesting to see, in case it is something that we can add to Darts :)

**Comment by nejox** [comment]
Thanks, that works for me, but I fell into another trap. I use checkpointing and after training I load the best epoch via `model.load_from_checkpoint(model_name="tft_multi_gpu", work_dir="tft_multi_gpu", best=True)`. 
No "best" checkpoint is created in the multi-GPU scenario.

**Comment by stompsjo** [comment]
I wanted to chime in to add a +1 on this issue. I was having similar issues and have recreated the error and fix with my scripts as well. I'll put a caveat here that I am also running darts as part of a [kedro](https://docs.kedro.org/en/stable/) pipeline, where training and testing occur in two separate nodes. There is always the possibility that kedro is interfering with the handling for multiprocessing (e.g. `torch.multiprocessing.freeze_support()`) but I am fairly confident I have isolated this to darts.

My error occurs when running `TFTModel.historical_forecast` and is the exact `TypeError` described above. I have verified that
- Running `historical_forecasts` with `accelerator=gpu, devices=auto, strategy=ddp` causes the `TypeError`.
- Running `historical_forecasts` with `accelerator=gpu, devices=0, strategy=auto` does not cause an error (i.e. switching from multi-GPU training to single GPU testing works).

However, the above hotfix **does not work** when using `TFTModel.historical_forecast`. I still end up with a `TypeError`on `darts.utils.historical_forecast._optimized_historical_forecasts` [line 131](https://github.com/unit8co/darts/blob/62122bea2f597ac1681e14712a095b88095d12bb/darts/utils/historical_forecasts/optimized_historical_forecasts_torch.py#L131). I think that again the main process is trying to run the method with `predictions=None` because the results from the discributed processes is not returned/processed. I tried adding to `_optimized_historical_forecasts` similar logic to above (`if predictions: ... else: return None`), but then I ended up with a PyTorch assertion error: `assert self.num_samples >= 1 or self.total_size == 0`. Is anyone else able to verify if the above fix works with `historical_forecasts`?

Also, I'm confused why the predictions need to be written to file with the BasePredictionWriter (maybe I should read the Lightning docs more closely). Is it possible for them to just be unified in memory?
