### ISSUE TITLE
[BUG] Optuna version?

### ISSUE THREAD

**Issue by jacktang** [unit8co/darts#2311]
**Describe the bug**
I followed https://github.com/unit8co/darts/blob/master/examples/17-hyperparameter-optimization.ipynb to combine optuna and darts. And it failed, the error log is listed as below

```
[I 2024-04-10 18:34:51,622] A new study created in memory with name: no-name-3b8568b0-d9e4-4482-9732-4e4893336c3b
[W 2024-04-10 18:34:52,831] Trial 0 failed with parameters: {'days_in': 5, 'days_out': 4, 'kernel_size': 18, 'num_filters': 18, 'weight_norm': False, 'dilation_base': 3, 'dropout': 0.018212297223904186, 'lr': 5.5937419871096e-05, 'dayofweek': True} because of the following error: TypeError("Trainer.__init__() got an unexpected keyword argument 'gpus'").
Traceback (most recent call last):
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_2134464/3852558938.py", line 22, in objective
    model = build_fit_tcn_model(
            ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_2134464/1198247613.py", line 75, in build_fit_tcn_model
    model.fit(
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/utils/torch.py", line 112, in decorator
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 751, in fit
    return self.fit_from_dataset(*params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/utils/torch.py", line 112, in decorator
    return decorated(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 957, in fit_from_dataset
    *self._setup_for_train(
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1066, in _setup_for_train
    trainer = self._setup_trainer(trainer, model, verbose, train_num_epochs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 543, in _setup_trainer
    return self._init_trainer(trainer_params=trainer_params, max_epochs=epochs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 556, in _init_trainer
    return pl.Trainer(
           ^^^^^^^^^^^
  File "/home/dev/miniconda3/envs/torch/lib/python3.11/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Trainer.__init__() got an unexpected keyword argument 'gpus'
[W 2024-04-10 18:34:52,832] Trial 0 failed with value None.
```

**To Reproduce**
```
!pip install -U darts
!pip install -U optuna
```
I also tried to downgrade optuna to `3.4.0`

**System (please complete the following information):**
 - Python version: 3.11.4
 - darts version: 0.28.0
 - optuna version: 3.4.0

**Comment by madtoinou** [comment]
Hi @jacktang,

I think that in this case, the problem doesn't come from optuna but pytorch-lightning. They slightly changed their API with one of their release (making the gpu accelerator part of this notebook obsolete), if you replace the `"gpu"` key with `"devices"` in the `pl_trainer_kwargs` dictionary, the problem should be solved (see [doc](https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api)).

**Comment by jacktang** [comment]
Thank you! the issue is fixed @madtoinou
