### ISSUE TITLE
[BUG] ValueError in metric calculation at series intersect slicing with custom frequency 

### ISSUE THREAD

**Issue by nejox** [unit8co/darts#2352]
**Describe the bug**
I have 3700 time series ranging differently between 2020 up to now with a custom frequency of business days created like this:
```
weekmask = 'Mon Tue Wed Thu Fri Sat'
freq = CustomBusinessDay(weekmask=weekmask)
```
Due to the fact that some covariates have maximum `n` length of the time series I predict only `n` time steps into the future at prediction time. This leds to the situation where my test time series may be longer than my prediction time series (in the case of this bug it was length 49 to length 48 only). In fact the prediction ranged to `Timestamp('2022-10-15 00:00:00', freq='C')` and the Test series ranged to `Timestamp('2022-10-17 00:00:00', freq='C')`. The call to rmse() then fails with `ValueError "The two time series must have at least a partially overlapping time index."` as the calculation of the intersection fails. `n_steps_between` returns 0 steps between the two timestamps. This seems to be only the case if the end dates fall onto a Saturday and a Monday (like the above timestamps)

**To Reproduce**
```
import darts.utils.timeseries_generation as tg
from pandas.tseries.offsets import CustomBusinessDay

weekmask = 'Mon Tue Wed Thu Fri Sat'
freq = CustomBusinessDay(weekmask=weekmask)

test = tg.linear_timeseries(start_value=1, end_value=2100, freq=freq, length=50)
preds = tg.linear_timeseries(start_value=1, end_value=2100, freq=freq, length=49)

from darts.metrics import rmse

rmse(test, preds)
```

**Expected behavior**
the correct intersection calculation should be that `n_steps_between()` returns 1 in this case and  both time series eventually have the same length, so that the rmse can be calculated. At least from my understanding. 

**System (please complete the following information):**
 - Python version: 3.9
 - darts version 0.29.0 (seems to be failing since the metric rework)

**Additional context**
I'm wondering, how would you generally handle a list of time series which may have various lengths and therefore their covariates have also different lengths at prediction? Do you need to find the smallest length to fill `n` time steps parameter at model prediction? 
I load historical sales data and cut this in train, val, test based on number of observations (48 in my case for test), as some days may be public holidays and thus i have missing days etc. The filling of missing days leads to some variation in lengths sometimes and that's how I ran into this problem.

**Comment by dennisbader** [comment]
Hi @nejox, thanks for this issue and very detailed report. I'll ivestigate it next week and come up with a fix.

**Comment by dennisbader** [comment]
Hi @nejox, which pandas version are you using?
With `pandas==2.2.2` for me your code snippet raises the following error:

```
Traceback (most recent call last):
  File "/Users/dennisbader/projects/unit8/darts_test_code/bug_fixes/bug_2352.py", line 12, in <module>
    rmse(test, preds)
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 142, in wrapper_multi_ts_support
    vals = _parallel_apply(
  File "/Users/dennisbader/projects/unit8/darts/darts/utils/utils.py", line 175, in _parallel_apply
    returned_data = Parallel(n_jobs=n_jobs)(
  File "/Users/dennisbader/miniconda3/envs/darts310_test/lib/python3.10/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
  File "/Users/dennisbader/miniconda3/envs/darts310_test/lib/python3.10/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 212, in wrapper_multivariate_support
    vals = func(*input_series, *args[num_series_in_args:], **kwargs)
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 1453, in rmse
    _get_wrapped_metric(mse)(
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 1160, in mse
    _get_wrapped_metric(se)(
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 1087, in se
    y_true, y_pred = _get_values_or_raise(
  File "/Users/dennisbader/projects/unit8/darts/darts/metrics/metrics.py", line 317, in _get_values_or_raise
    vals_a_common = series_a.slice_intersect_values(series_b, copy=make_copy)
  File "/Users/dennisbader/projects/unit8/darts/darts/timeseries.py", line 2517, in slice_intersect_values
    start, end = self._slice_intersect_bounds(other)
  File "/Users/dennisbader/projects/unit8/darts/darts/timeseries.py", line 2523, in _slice_intersect_bounds
    shift_start = n_steps_between(
  File "/Users/dennisbader/projects/unit8/darts/darts/utils/utils.py", line 367, in n_steps_between
    raise_log(
  File "/Users/dennisbader/projects/unit8/darts/darts/logging.py", line 132, in raise_log
    raise exception
ValueError: Cannot infer period alias for `freq=<CustomBusinessDay>`. Is it a valid pandas offset/frequency alias?
```

```

**Comment by nejox** [comment]
Ah, I'm using pandas 1.5.3 - that's interesting..
