### ISSUE TITLE
[BUG]When I install Darts I get this error 

### ISSUE THREAD

**Issue by YessicaCh** [unit8co/darts#328]
**Describe the bug**
I installed it the first time and it worked, now I can't install with the classic one 
`pip install darts`

**To Reproduce**
`Collecting torch==1.7.1
SystemError: deallocated bytearray object has exported buffers
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in __init__
    version=version,
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 552, in _prepare_linked_requirement
    self.download_dir, hashes
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 243, in unpack_url
    hashes=hashes,
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/network/download.py", line 144, in __call__
    resp = _http_get_download(self._session, link)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/network/download.py", line 125, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_internal/network/session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 44, in send
    cached_response = self.controller.cached_request(request)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/cachecontrol/controller.py", line 145, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 97, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 184, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 129, in unpackb
    ret = unpacker._unpack()
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 671, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 671, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 625, in _unpack
    typ, n, obj = self._read_header(execute)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 468, in _read_header
    obj = self._read(n)
  File "/home/ec2-user/environment/one_elastic/mongo/env_req/lib/python3.6/site-packages/pip/_vendor/msgpack/fallback.py", line 376, in _read
    ret = self._buffer[i : i + n]
MemoryError`
**Expected behavior**

**System (please complete the following information):**
 - Python version: 3.6.1
 - darts version darts==0.6.1

**Additional context**

**Comment by hrzn** [comment]
You need Python 3.7+ for installing `darts`. Try updating your Python version first and installing again.
