### ISSUE TITLE
[BUG] Cannot install darts in jupyter notebook

### ISSUE THREAD

**Issue by NikolaMaroski** [unit8co/darts#506]
**Describe the bug**
Cannot install darts in jupyter notebook

**To Reproduce**

pip install darts

returns ....
    Building wheels for collected packages: prophet
      Building wheel for prophet (setup.py): started
      Building wheel for prophet (setup.py): finished with status 'error'
      Running setup.py clean for prophet
    Failed to build prophet
    Installing collected packages: prophet
        Running setup.py install for prophet: started
        Running setup.py install for prophet: finished with status 'error'

**Comment by NikolaMaroski** [comment]
Full error message:

 File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\prophet\models.py", line 228, in build_model
      import pystan
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\pystan\__init__.py", line 9, in <module>
      from pystan.api import stanc, stan
    File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\pystan\api.py", line 13, in <module>
      import pystan._api  # stanc wrapper
  ImportError: DLL load failed while importing _api: The specified module could not be found.
  ----------------------------------------
  ERROR: Failed building wheel for prophet
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nikola\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nikola\\AppData\\Local\\Temp\\pip-install-qy4hvng1\\prophet_01b494c39ba2468cb1681d6a214b6a91\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nikola\\AppData\\Local\\Temp\\pip-install-qy4hvng1\\prophet_01b494c39ba2468cb1681d6a214b6a91\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Nikola\AppData\Local\Temp\pip-record-_nx4i7cq\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\nikola\appdata\local\programs\python\python38\Include\prophet'
         cwd: C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\prophet
    creating build\lib\prophet\stan_model
    Importing plotly failed. Interactive plots will not work.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\setup.py", line 123, in <module>
        setup(
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "C:\Users\Nikola\AppData\Local\Temp\pip-install-qy4hvng1\prophet_01b494c39ba2468cb1681d6a214b6a91\prophet\models.py", line 228, in build_model
        import pystan
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "c:\users\nikola\appdata\local\programs\python\python38\lib\site-packages\pystan\api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed while importing _api: The specified module could not be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\nikola\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nikola\\AppData\\Local\\Temp\\pip-install-qy4hvng1\\prophet_01b494c39ba2468cb1681d6a214b6a91\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nikola\\AppData\\Local\\Temp\\pip-install-qy4hvng1\\prophet_01b494c39ba2468cb1681d6a214b6a91\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Nikola\AppData\Local\Temp\pip-record-_nx4i7cq\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\nikola\appdata\local\programs\python\python38\Include\prophet' Check the logs for full command output.

**Comment by inigohidalgo** [comment]
For anybody trying to install darts on windows without a conda environment, the dependencies which do not work well are prophet (due to pystan) and possibly pytorch-related libraries. If you do not need support for those methods, you can install subsets of darts functionality as explained in https://github.com/unit8co/darts/blob/master/INSTALL.md#from-pypi

  
>* Install core only (without neural networks, Prophet or AutoARIMA): `pip install u8darts`
>* Install core + neural networks (PyTorch): `pip install "u8darts[torch]"`
>* Install core + Facebook Prophet: `pip install "u8darts[prophet]"`
>* Install core + AutoARIMA: `pip install "u8darts[pmdarima]"`
