### ISSUE TITLE
[BUG] unexpected keyword argument 'pl_trainer_kwargs'

### ISSUE THREAD

**Issue by JohansonB** [unit8co/darts#914]
I'm trying to run the provided neural network models on my GPU instead of CPU. The API reference tells me to specify the 'pl_trainer_kwargs' argument, but when I execute following command:
forecaster = TCNModel(input_chunk, output_len, kernel_size=kernel_size,pl_trainer_kwargs={
"accelerator": "gpu",
"gpus": [0]
})
I get following error:
Traceback (most recent call last):
File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 154, in
main()
File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 39, in main
runTime, y_pred = darts()
File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 100, in darts
forecaster = TCNModel(input_chunk, output_len, kernel_size=kernel_size,pl_trainer_kwargs={
File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\forecasting_model.py", line 41, in call
return super(ModelMeta, cls).call(*args, **kwargs)
File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\utils\torch.py", line 65, in decorator
return decorated(self, *args, **kwargs)
File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\tcn_model.py", line 336, in init
super().init(likelihood=likelihood, **kwargs)
File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\torch_forecasting_model.py", line 1131, in init
super().init(**kwargs)
TypeError: init() got an unexpected keyword argument 'pl_trainer_kwargs'

I copy pasted 'pl_trainer_kwargs' from the API reference so im pretty sure I didnt just make a typo mistake

**System (please complete the following information):**
 - Python version: 3.8
 - darts version 0.15.0
-torch version 1.11.0+cu113

**Comment by JohansonB** [comment]
I'm trying to run the provided neural network models on my GPU instead of CPU. The API reference tells me to specify the 'pl_trainer_kwargs' argument, but when I execute following command: 
forecaster = TCNModel(input_chunk,  output_len, kernel_size=kernel_size,pl_trainer_kwargs={
            "accelerator": "gpu",
            "gpus": [0]
        })
I get following error:
Traceback (most recent call last):
  File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 154, in <module>
    main()
  File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 39, in main
    runTime, y_pred = darts()
  File "C:/Users/41766/PycharmProjects/pythonProject1/DARTS/DartsModel.py", line 100, in darts
    forecaster = TCNModel(input_chunk,  output_len, kernel_size=kernel_size,pl_trainer_kwargs={
  File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\forecasting_model.py", line 41, in __call__
    return super(ModelMeta, cls).__call__(*args, **kwargs)
  File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\utils\torch.py", line 65, in decorator
    return decorated(self, *args, **kwargs)
  File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\tcn_model.py", line 336, in __init__
    super().__init__(likelihood=likelihood, **kwargs)
  File "C:\Users\41766\PycharmProjects\pythonProject1\venv\lib\site-packages\darts\models\forecasting\torch_forecasting_model.py", line 1131, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'pl_trainer_kwargs'

I copy pasted 'pl_trainer_kwargs' from the API reference so im pretty sure I didnt just make a typo mistake

**Comment by hrzn** [comment]
Hi, your version of Darts is too old. Please update doing : `pip install -U darts`

**Comment by JohansonB** [comment]
thank you for your fast response. This fixed the issue for nearly all models. With N-Beats the issue some how still remains.
