### ISSUE TITLE
[BUG] Historical forecasts for model that has not previously been fitted

### ISSUE THREAD

**Issue by ludomitch** [unit8co/darts#994]
**Describe the bug**
In the [docs](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.historical_forecasts) for historical forecasts, it is said that:

> By default, this method always re-trains the models on the entire available history, corresponding to an expanding window strategy. If retrain is set to False, the model will only be trained on the initial training window (up to start time stamp), and only if it has not been trained before. This is not supported by all models.

What are the models for which this is not supported? I have tried for both TFT and linear regression and both give different errors. Is this expected functionality or should it work without previously fitting? 

**To Reproduce**
```
quantiles = [
    0.05,
    0.95,
]
input_chunk_length = 24
forecast_horizon = 12
my_model = TFTModel(
    input_chunk_length=input_chunk_length,
    output_chunk_length=forecast_horizon,
    hidden_size=64,
    lstm_layers=1,
    num_attention_heads=4,
    dropout=0.1,
    batch_size=16,
    n_epochs=300,
    add_relative_index=False,
    add_encoders=None,
    likelihood=QuantileRegression(
        quantiles=quantiles
    random_state=42,
)
my_model.historical_forecasts(target, past_covariates, future_covariates, retrain=False)
```
**Expected behavior**
My desired functionality is that I can run the historical forecasts method without previously having trained the model. When I run historical_forecasts it trains the model on the data given up until the start time stamp, as mentioned in the docs. 

**System (please complete the following information):**
 - Python version: 3.8.10
 - darts version: u8darts==0.19.0

**Additional context**
For TFT, the error seems to arise because rather than using `train_sample` off the training set given to historical_forecasts, it is doing it off `self.train_sample` which is None because the model hasn't previously been fitted.
Traceback:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ludo/Desktop/ml_ops/debugger.py", line 63, in <module>
    model.backtest(retrain=False, plotting=True, batch_number="mambo1")
  File "/Users/ludo/Desktop/ml_ops/ml_models/forecast/darts_model.py", line 412, in backtest
    return super().backtest(
  File "/Users/ludo/Desktop/ml_ops/ml_models/forecast/base_model.py", line 317, in backtest
    historical_forecasts = self.model.historical_forecasts(
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/utils/utils.py", line 172, in sanitized_method
    return method_to_sanitize(self, *only_args.values(), **only_kwargs)
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/forecasting_model.py", line 445, in historical_forecasts
    forecast = self._predict_wrapper(
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/forecasting_model.py", line 1042, in _predict_wrapper
    return self.predict(
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/tft_model.py", line 944, in predict
    return super().predict(n, *args, **kwargs)
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/utils/torch.py", line 70, in decorator
    return decorated(self, *args, **kwargs)
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1100, in predict
    predictions = self.predict_from_dataset(
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/utils/torch.py", line 70, in decorator
    return decorated(self, *args, **kwargs)
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1186, in predict_from_dataset
    self._verify_predict_sample(input_series_dataset[0])
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1834, in _verify_predict_sample
    _mixed_compare_sample(self.train_sample, predict_sample)
  File "/Users/ludo/Desktop/ml_ops/venv/lib/python3.8/site-packages/darts/models/forecasting/torch_forecasting_model.py", line 1544, in _mixed_compare_sample
    train_has_ds = [ds is not None for ds in train_sample[:-1]]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dennisbader** [comment]
You have to set `retrain=True` (or don't set it -> default) which will retrain/train the models

**Comment by ludomitch** [comment]
I don't want to retrain on each split though, just on the first training window as explained in the docs–which would require retrain=False, right?

**Comment by hrzn** [comment]
The error with TFT looks like a bug indeed.

**Comment by dennisbader** [comment]
#1005 should fix this. Was a general issue with `historical_forecasts` not calling fit if model hasn't been fit before and `retrain=False`.
